name: sjoleee CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Node.js 22.x로 업데이트
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4  # v4로 업데이트

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4  # v4로 업데이트
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >>$GITHUB_OUTPUT

      - uses: actions/cache@v4  # v4로 업데이트
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install the project dependencies
        run: yarn install

      - name: Prettier check
        run: yarn prettier

      - name: Lint check
        run: yarn lint

      - name: TS check
        run: yarn tsc